<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Dt_rv_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_board by B_id
     */
    function get_tb_board($R_id)
    {
        return $this->db->get_where('tb_review',array('R_id'=>$R_id))->row_array();
    }

    /*
     * Get all tb_board
     */
    function get_all_tb_board()
    {
        return $this->db->get('tb_review')->result_array();
    }

    /*
     * function to add new tb_board
     */
    function add_tb_board($params)
    {
        $this->db->insert('tb_review',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update tb_board
     */
    function update_tb_board($rId,$params)
    {
        $this->db->where('R_id',$rId);
        $response = $this->db->update('tb_review',$params);
        if($response)
        {
            return "tb_board updated successfully";
        }
        else
        {
            return "Error occuring while updating tb_board";
        }
    }

    /*
     * function to delete tb_board
     */
    function delete_tb_board($rId)
    {
        $response = $this->db->delete('tb_board',array('R_id'=>$rId));
        if($response)
        {
            return "tb_board deleted successfully";
        }
        else
        {
            return "Error occuring while deleting tb_board";
        }
    }
}
