<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Edit_promember_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_member by M_user
     */
    function get_tb_member($M_user)
    {
        return $this->db->get_where('tb_member',array('M_user'=>$M_user))->row_array();
    }
    
    /*
     * Get all tb_member
     */
    function get_all_tb_member()
    {
        return $this->db->get('tb_member')->result_array();
    }
    
    /*
     * function to add new tb_member
     */
    function add_tb_member($params)
    {
        $this->db->insert('tb_member',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_member
     */
    function update_tb_member($M_user,$params)
    {
        $this->db->where('M_user',$M_user);
        $response = $this->db->update('tb_member',$params);
        if($response)
        {
            return "tb_member updated successfully";
        }
        else
        {
            return "Error occuring while updating tb_member";
        }
    }
    
    /*
     * function to delete tb_member
     */
    function delete_tb_member($M_user)
    {
        $response = $this->db->delete('tb_member',array('M_user'=>$M_user));
        if($response)
        {
            return "tb_member deleted successfully";
        }
        else
        {
            return "Error occuring while deleting tb_member";
        }
    }
}
