<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Edit_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_category by C_id
     */
    function get_tb_category($C_id)
    {
        return $this->db->get_where('tb_category',array('C_id'=>$C_id))->row_array();
    }
    
    /*
     * Get all tb_category
     */
    function get_all_tb_category()
    {
        return $this->db->get('tb_category')->result_array();
    }
    
    /*
     * function to add new tb_category
     */
    function add_tb_category($params)
    {
        $this->db->insert('tb_category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_category
     */
    function update_tb_category($C_id,$params)
    {
        $this->db->where('C_id',$C_id);
        $response = $this->db->update('tb_category',$params);
        if($response)
        {
            return "tb_category updated successfully";
        }
        else
        {
            return "Error occuring while updating tb_category";
        }
    }
    
    /*
     * function to delete tb_category
     */
    function delete_tb_category($C_id)
    {
        $response = $this->db->delete('tb_category',array('C_id'=>$C_id));
        if($response)
        {
            return "tb_category deleted successfully";
        }
        else
        {
            return "Error occuring while deleting tb_category";
        }
    }
}
